# docker-compose.yml

version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: 'postgres://requ:1234@postgres:5432/requ'
      JWT_SECRET: 'my-secret'
      PORT: 8000
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: requ
      POSTGRES_USER: requ
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
