version: '3.8'
services:
  postgres:
    build:
      context: ./postgres # Directory containing the PostgreSQL Dockerfile
    restart: always
    environment:
      POSTGRES_USER: requ
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
