# Dockerfile.migrate

FROM node:18-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache bash ncurses

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma/

RUN pnpm install

COPY . .

RUN npx prisma generate

CMD ["sh", "-c", "while ! nc -z postgres 5432; do sleep 1; done; npx prisma migrate dev --name init"]
