version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: 'postgres://koyeb-adm:k4ZMJcuNePD7@ep-soft-union-a1d89bbn.ap-southeast-1.pg.koyeb.app/koyebdb'
      JWT_SECRET: 'my-secret'
      PORT: 8000
    depends_on:
      - migrate
    networks:
      - backend

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      DATABASE_URL: 'postgres://koyeb-adm:k4ZMJcuNePD7@ep-soft-union-a1d89bbn.ap-southeast-1.pg.koyeb.app/koyebdb'
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: koyebdb
      POSTGRES_USER: koyeb-adm
      POSTGRES_PASSWORD: k4ZMJcuNePD7
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
