# Dockerfile.migrate

FROM node:18-alpine

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma/

RUN pnpm install

COPY . .

RUN npx prisma generate

CMD ["sh", "-c", "npx prisma migrate dev --name init && pnpm run start:prod"]
