version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: 'postgres://requ:1234@postgres:5432/requ'
      JWT_SECRET: 'my-secret'
      PORT: 8000
    depends_on:
      - postgres
    networks:
      - backend

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      DATABASE_URL: 'postgres://requ:1234@postgres:5432/requ'
    depends_on:
      - postgres
    networks:
      - backend
    command:
      [
        'sh',
        '-c',
        'while !</dev/tcp/postgres/5432; do sleep 1; done; npx prisma migrate dev --name init',
      ]

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: requ
      POSTGRES_USER: requ
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
